name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go install ./cmd/go-observability-bench 

    - name: Fast Bench
      run: go-observability-bench ./fast.yaml fast

    - uses: actions/upload-artifact@v2
      with:
        name: results
        path: fast
