name: Bench Fast

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dd-agent:
        image: datadog/agent:latest
        ports:
          - 8126:8126
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_INSIDE_CI: true
          DD_HOSTNAME: "go-observability-bench"
          DD_SERVICE: "go-observability-bench"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go install ./cmd/go-observability-bench 

    - name: Bench
      run: go-observability-bench ./fast.yaml fast

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: fast
